from __future__ import annotations

import json
from pathlib import Path

import pytest

pytestmark = pytest.mark.packaging

OPENAPI_FILE = Path(__file__).resolve().parents[3] / "pg_anon" / "rest_api" / "openapi.json"

REGENERATE_HINT = "The committed OpenAPI schema is stale. Regenerate it with `make openapi` and commit the result."


@pytest.fixture(scope="module")
def committed_schema() -> dict:
    """The OpenAPI schema stored in the repository."""
    if not OPENAPI_FILE.is_file():
        pytest.fail(f"{OPENAPI_FILE} is missing. {REGENERATE_HINT}")
    return json.loads(OPENAPI_FILE.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def generated_schema() -> dict:
    """The OpenAPI schema the current REST app produces."""
    pytest.importorskip("fastapi", reason="REST API extra is not installed")
    from pg_anon.rest_api.api import app

    return app.openapi()


def test_committed_openapi_matches_the_app(committed_schema, generated_schema):
    """The schema is generated by hand, so nothing but this test keeps it honest."""
    assert committed_schema == generated_schema, REGENERATE_HINT


def test_openapi_covers_every_route(generated_schema):
    """Every non-internal route reaches the schema; a missing one means a broken decorator."""
    pytest.importorskip("fastapi", reason="REST API extra is not installed")
    from pg_anon.rest_api.api import app

    internal = {"/openapi.json", "/docs", "/docs/oauth2-redirect", "/redoc"}
    routes = {route.path for route in app.routes if getattr(route, "methods", None)} - internal

    assert routes == set(generated_schema["paths"])
