from enum import Enum


class ErrorCode(str, Enum):
    # Dictionary
    NO_DICT_FILES = "NO_DICT_FILES"
    INVALID_META_DICT = "INVALID_META_DICT"
    INVALID_DICT_FILE = "INVALID_DICT_FILE"

    # Preview
    TABLE_EXCLUDED = "TABLE_EXCLUDED"
    TABLE_NOT_FOUND = "TABLE_NOT_FOUND"
    INVALID_LIMIT = "INVALID_LIMIT"
    INVALID_OFFSET = "INVALID_OFFSET"

    # Database
    DB_CONNECTION_FAILED = "DB_CONNECTION_FAILED"
    DB_QUERY_FAILED = "DB_QUERY_FAILED"
    INSUFFICIENT_CONNECTIONS = "INSUFFICIENT_CONNECTIONS"

    # Config / Paths
    INVALID_CONFIG = "INVALID_CONFIG"
    INVALID_FILE_FORMAT = "INVALID_FILE_FORMAT"
    INVALID_PATH = "INVALID_PATH"

    # PG tools
    PG_TOOLS_NOT_FOUND = "PG_TOOLS_NOT_FOUND"
    SCHEMA_NOT_INITIALIZED = "SCHEMA_NOT_INITIALIZED"

    # Dump
    OUTPUT_DIR_NOT_EMPTY = "OUTPUT_DIR_NOT_EMPTY"
    INVALID_OUTPUT_DIR = "INVALID_OUTPUT_DIR"
    NO_OBJECTS_FOR_DUMP = "NO_OBJECTS_FOR_DUMP"
    DUMP_FAILED = "DUMP_FAILED"
    DUMP_QUERY_FAILED = "DUMP_QUERY_FAILED"
    COMPRESSION_FAILED = "COMPRESSION_FAILED"

    # Restore
    INPUT_DIR_NOT_FOUND = "INPUT_DIR_NOT_FOUND"
    DB_NOT_EMPTY = "DB_NOT_EMPTY"
    INSUFFICIENT_DISK_SPACE = "INSUFFICIENT_DISK_SPACE"
    VERSION_INCOMPATIBLE = "VERSION_INCOMPATIBLE"
    RESTORE_FAILED = "RESTORE_FAILED"
    EXTENSION_ERROR = "EXTENSION_ERROR"
    ROW_COUNT_MISMATCH = "ROW_COUNT_MISMATCH"
    VALIDATION_FAILED = "VALIDATION_FAILED"

    # Scan
    NO_OBJECTS_FOR_SCAN = "NO_OBJECTS_FOR_SCAN"
    SCAN_FIELD_ERROR = "SCAN_FIELD_ERROR"

    # General
    UNKNOWN_MODE = "UNKNOWN_MODE"
    OPERATION_FAILED = "OPERATION_FAILED"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class PgAnonError(Exception):
    def __init__(self, code: ErrorCode, message: str):
        self.code = code
        self.message = message
        super().__init__(message)

    def __reduce__(self):
        return (self.__class__, (self.code, self.message))
