{
	"include_rules": [
		{
			"schema": "schm_other_3",
			"table": "data_types_test",
		}
	],
	"field": {
		"rules": [".*"]
	},
	"funcs": {
        "default": "anon_funcs.digest(\"%s\", 'default', 'md5')",
        "bit": "anon_funcs.digest(\"%s\", 'bit', 'md5')",
        "varbit": "anon_funcs.digest(\"%s\", 'varbit', 'md5')",
        "bool": "anon_funcs.digest(\"%s\", 'bool', 'md5')",
        "char": "anon_funcs.digest(\"%s\", 'char', 'md5')",
        "varchar": "anon_funcs.digest(\"%s\", 'varchar', 'md5')",
        "int": "anon_funcs.digest(\"%s\", 'int', 'md5')",
        "int4": "anon_funcs.digest(\"%s\", 'int4', 'md5')",
        "int2": "anon_funcs.digest(\"%s\", 'int2', 'md5')",
        "int8": "anon_funcs.digest(\"%s\", 'int8', 'md5')",
        "float": "anon_funcs.digest(\"%s\", 'float', 'md5')",
        "float8": "anon_funcs.digest(\"%s\", 'float8', 'md5')",
        "float4": "anon_funcs.digest(\"%s\", 'float4', 'md5')",
        "decimal": "anon_funcs.digest(\"%s\", 'decimal', 'md5')",
        "dec": "anon_funcs.digest(\"%s\", 'dec', 'md5')",
        "serial2": "anon_funcs.digest(\"%s\", 'serial2', 'md5')",
        "serial4": "anon_funcs.digest(\"%s\", 'serial4', 'md5')",
        "serial8": "anon_funcs.digest(\"%s\", 'serial8', 'md5')",
        "time": "anon_funcs.digest(\"%s\", 'time', 'md5')",
        "timetz": "anon_funcs.digest(\"%s\", 'timetz', 'md5')",
        "timestamp": "anon_funcs.digest(\"%s\", 'timestamp', 'md5')",
        "timestamptz": "anon_funcs.digest(\"%s\", 'timestamptz', 'md5')",
        "bit(4)": "anon_funcs.digest(\"%s\", 'bit(4)', 'md5')",
        "bit(5)": "anon_funcs.digest(\"%s\", 'bit(5)', 'md5')",
        "bit(6)": "anon_funcs.digest(\"%s\", 'bit(6)', 'md5')",
        "varbit(4)": "anon_funcs.digest(\"%s\", 'varbit(4)', 'md5')",
        "varbit(5)": "anon_funcs.digest(\"%s\", 'varbit(5)', 'md5')",
        "varbit(6)": "anon_funcs.digest(\"%s\", 'varbit(6)', 'md5')",
        "char(4)": "anon_funcs.digest(\"%s\", 'char(4)', 'md5')",
        "char(5)": "anon_funcs.digest(\"%s\", 'char(5)', 'md5')",
        "char(6)": "anon_funcs.digest(\"%s\", 'char(6)', 'md5')",
        "varchar(19)": "anon_funcs.digest(\"%s\", 'varchar(19)', 'md5')",
        "varchar(20)": "anon_funcs.digest(\"%s\", 'varchar(20)', 'md5')",
        "varchar(21)": "anon_funcs.digest(\"%s\", 'varchar(21)', 'md5')",
        "decimal(10,1)": "anon_funcs.digest(\"%s\", 'decimal(10,1)', 'md5')",
        "decimal(10,2)": "anon_funcs.digest(\"%s\", 'decimal(10,2)', 'md5')",
        "decimal(11,2)": "anon_funcs.digest(\"%s\", 'decimal(11,2)', 'md5')",
        "time(2)": "anon_funcs.digest(\"%s\", 'time(2)', 'md5')",
        "time(3)": "anon_funcs.digest(\"%s\", 'time(3)', 'md5')",
        "time(4)": "anon_funcs.digest(\"%s\", 'time(4)', 'md5')",
        "timestamp(2)": "anon_funcs.digest(\"%s\", 'timestamp(2)', 'md5')",
        "timestamp(3)": "anon_funcs.digest(\"%s\", 'timestamp(3)', 'md5')",
        "timestamp(4)": "anon_funcs.digest(\"%s\", 'timestamp(4)', 'md5')",
        "timestamptz(2)": "anon_funcs.digest(\"%s\", 'timestamptz(2)', 'md5')",
        "timestamptz(3)": "anon_funcs.digest(\"%s\", 'timestamptz(3)', 'md5')",
        "timestamptz(4)": "anon_funcs.digest(\"%s\", 'timestamptz(4)', 'md5')",
        "timetz(2)": "anon_funcs.digest(\"%s\", 'timetz(2)', 'md5')",
        "timetz(3)": "anon_funcs.digest(\"%s\", 'timetz(3)', 'md5')",
        "timetz(4)": "anon_funcs.digest(\"%s\", 'timetz(4)', 'md5')",
    }
}
